### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by Gelmo** [crashbuggy/kiwiirc#1]
Running this image via Rancher. Container port 8080 has been mapped to a new port for tcp and udp. When going to server:port I receive a 404 error. Any suggestions?

**Comment by FingerlessGlov3s** [comment]
getting same problem.

/webirc/kiwiirc/
gets you "Welcome to SockJS!", still no better lol

**Comment by kaitlinsm** [comment]
There isn't anything serving the web content in the default configuration.

Try editing `config.conf`, setting
```
[fileserving]
enabled = true
webroot = www/
```

You should then be able to just hit whatever port you've mapped to your host and it should all work.

**Comment by crashbuggy** [comment]
sorry @Gelmo and @FingerlessGlov3s , I didn't see this issue until now. and thanks @kaitlinsm for helping out.

I guess you've either fixed it or moved on.

**Comment by Gelmo** [comment]
@crashbuggy No worries, and my particular issue was a misconfiguration on my end. Sorry for not posting an update! Hopefully this doesn't re-open this issue...
